// leap-angular/src/components/shared/CommentaryDrawer.tsx
import { useEffect } from 'react'
import { Drawer, Form, Input, Button, List, Avatar } from 'antd'
import { SaveOutlined, UserOutlined } from '@ant-design/icons'
import dayjs from 'dayjs'
import './CommentaryDrawer.scss'

const { TextArea } = Input

export interface Commentary {
  id: number
  user: string
  timestamp: Date
  content: string
}

interface CommentaryDrawerProps {
  isOpen: boolean
  historyComments: Commentary[]
  productName?: string
  onClose: () => void
  onSave: (content: string) => void
}

function CommentaryDrawer({
  isOpen,
  historyComments,
  productName = '',
  onClose,
  onSave,
}: CommentaryDrawerProps) {
  const [form] = Form.useForm()

  useEffect(() => {
    if (!isOpen) {
      form.resetFields()
    }
  }, [isOpen, form])

  const handleSave = () => {
    form.validateFields().then((values) => {
      onSave(values.content)
      form.resetFields()
    })
  }

  const handleCancel = () => {
    form.resetFields()
    onClose()
  }

  return (
    <Drawer
      title={`Commentary - ${productName}`}
      placement="right"
      onClose={onClose}
      open={isOpen}
      width={480}
      className="commentary-drawer"
      footer={
        <div className="drawer-footer">
          <Button onClick={handleCancel}>Cancel</Button>
          <Button
            type="primary"
            onClick={handleSave}
            icon={<SaveOutlined />}
            disabled={!form.getFieldValue('content') || form.getFieldValue('content').length < 10}
          >
            Save
          </Button>
        </div>
      }
    >
      <div className="drawer-body">
        {historyComments.length > 0 && (
          <div className="history-section">
            <h4 className="section-title">History</h4>
            <List
              dataSource={historyComments}
              renderItem={(comment) => (
                <List.Item className="comment-item">
                  <List.Item.Meta
                    avatar={<Avatar icon={<UserOutlined />} />}
                    title={
                      <div className="comment-header">
                        <span className="user-name">{comment.user}</span>
                        <span className="comment-time">
                          {dayjs(comment.timestamp).format('MMM D, YYYY HH:mm')}
                        </span>
                      </div>
                    }
                    description={<div className="comment-content">{comment.content}</div>}
                  />
                </List.Item>
              )}
            />
          </div>
        )}

        <div className="new-comment-section">
          <h4 className="section-title">Add New Commentary</h4>
          <Form form={form} layout="vertical">
            <Form.Item
              name="content"
              rules={[
                { required: true, message: 'Commentary is required' },
                { min: 10, message: 'Minimum 10 characters required' },
              ]}
            >
              <TextArea
                rows={6}
                placeholder="Enter your commentary here..."
                showCount
                maxLength={1000}
              />
            </Form.Item>
          </Form>
        </div>
      </div>
    </Drawer>
  )
}

export default CommentaryDrawer

// leap-angular/src/app/shared/components/commentary-drawer/commentary-drawer.component.ts
import { Component, EventEmitter, Input, Output, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

export interface Commentary {
  id: number;
  user: string;
  timestamp: Date;
  content: string;
}

@Component({
  selector: 'app-commentary-drawer',
  templateUrl: './commentary-drawer.component.html',
  styleUrls: ['./commentary-drawer.component.scss']
})
export class CommentaryDrawerComponent implements OnInit {
  @Input() isOpen = false;
  @Input() historyComments: Commentary[] = [];
  @Input() productName = '';
  @Output() close = new EventEmitter<void>();
  @Output() save = new EventEmitter<string>();

  commentForm!: FormGroup;

  constructor(private fb: FormBuilder) {}

  ngOnInit(): void {
    this.commentForm = this.fb.group({
      content: ['', [Validators.required, Validators.minLength(10)]]
    });
  }

  onClose(): void {
    this.close.emit();
  }

  onSave(): void {
    if (this.commentForm.valid) {
      this.save.emit(this.commentForm.value.content);
      this.commentForm.reset();
    }
  }

  onCancel(): void {
    this.commentForm.reset();
    this.close.emit();
  }
}

<div class="commentary-drawer" [class.open]="isOpen">
  <div class="drawer-overlay" (click)="onClose()"></div>

  <div class="drawer-content" [@slideIn]>
    <!-- Header -->
    <div class="drawer-header">
      <h3>Commentary - {{ productName }}</h3>
      <button mat-icon-button (click)="onClose()" class="close-button">
        <mat-icon>close</mat-icon>
      </button>
    </div>

    <!-- History Comments (Read-only) -->
    <div class="drawer-body">
      <div class="history-section" *ngIf="historyComments.length > 0">
        <h4 class="section-title">History</h4>
        <div class="comment-list">
          <div class="comment-item" *ngFor="let comment of historyComments">
            <div class="comment-header">
              <div class="comment-user">
                <mat-icon class="user-icon">person</mat-icon>
                <span class="user-name">{{ comment.user }}</span>
              </div>
              <span class="comment-time">{{ comment.timestamp | date: 'MMM d, y HH:mm' }}</span>
            </div>
            <div class="comment-content">{{ comment.content }}</div>
          </div>
        </div>
      </div>

      <!-- New Comment Form -->
      <div class="new-comment-section">
        <h4 class="section-title">Add New Commentary</h4>
        <form [formGroup]="commentForm">
          <mat-form-field appearance="outline" class="comment-field">
            <mat-label>Commentary</mat-label>
            <textarea
              matInput
              formControlName="content"
              rows="6"
              placeholder="Enter your commentary here..."
            ></textarea>
            <mat-hint>Minimum 10 characters required</mat-hint>
            <mat-error *ngIf="commentForm.get('content')?.hasError('required')">
              Commentary is required
            </mat-error>
            <mat-error *ngIf="commentForm.get('content')?.hasError('minlength')">
              Minimum 10 characters required
            </mat-error>
          </mat-form-field>
        </form>
      </div>
    </div>

    <!-- Footer Actions -->
    <div class="drawer-footer">
      <button mat-stroked-button (click)="onCancel()" class="cancel-button">
        Cancel
      </button>
      <button
        mat-raised-button
        color="primary"
        (click)="onSave()"
        [disabled]="!commentForm.valid"
        class="save-button"
      >
        <mat-icon>save</mat-icon>
        Save
      </button>
    </div>
  </div>
</div>
