// leap-angular/src/components/shared/StatusBadge.tsx
import { Tag } from 'antd'
import {
  EditOutlined,
  ClockCircleOutlined,
  CheckCircleOutlined,
  CloseCircleOutlined,
  RiseOutlined,
} from '@ant-design/icons'
import { WorkflowStatus } from '@store/slices/workflowSlice'
import './StatusBadge.scss'

interface StatusBadgeProps {
  status: WorkflowStatus
}

interface StatusConfig {
  label: string
  icon: React.ReactNode
  color: string
}

const statusMap: Record<WorkflowStatus, StatusConfig> = {
  draft: {
    label: 'Draft',
    icon: <EditOutlined />,
    color: 'default',
  },
  pending: {
    label: 'Pending Review',
    icon: <ClockCircleOutlined />,
    color: 'processing',
  },
  approved: {
    label: 'Approved',
    icon: <CheckCircleOutlined />,
    color: 'success',
  },
  rejected: {
    label: 'Rejected',
    icon: <CloseCircleOutlined />,
    color: 'error',
  },
  escalated: {
    label: 'Escalated',
    icon: <RiseOutlined />,
    color: 'warning',
  },
}

function StatusBadge({ status }: StatusBadgeProps) {
  const config = statusMap[status] || statusMap.draft

  return (
    <Tag
      icon={config.icon}
      color={config.color}
      className={`status-badge ${status}`}
    >
      {config.label}
    </Tag>
  )
}

export default StatusBadge

// leap-angular/src/app/shared/components/status-badge/status-badge.component.ts
import { Component, Input } from '@angular/core';

export type WorkflowStatus = 'draft' | 'pending' | 'approved' | 'rejected' | 'escalated';

interface StatusConfig {
  label: string;
  icon: string;
  class: string;
}

@Component({
  selector: 'app-status-badge',
  templateUrl: './status-badge.component.html',
  styleUrls: ['./status-badge.component.scss']
})
export class StatusBadgeComponent {
  @Input() status: WorkflowStatus = 'draft';

  private readonly statusMap: Record<WorkflowStatus, StatusConfig> = {
    draft: { label: 'Draft', icon: 'edit', class: 'draft' },
    pending: { label: 'Pending Review', icon: 'schedule', class: 'pending' },
    approved: { label: 'Approved', icon: 'check_circle', class: 'approved' },
    rejected: { label: 'Rejected', icon: 'cancel', class: 'rejected' },
    escalated: { label: 'Escalated', icon: 'trending_up', class: 'escalated' }
  };

  get config(): StatusConfig {
    return this.statusMap[this.status] || this.statusMap.draft;
  }
}

<span class="status-badge" [ngClass]="config.class">
  <mat-icon class="status-icon">{{ config.icon }}</mat-icon>
  <span class="status-label">{{ config.label }}</span>
</span>
