// leap-angular/src/components/layout/Sidebar.tsx
import { Layout } from 'antd'
import { MenuFoldOutlined, MenuUnfoldOutlined } from '@ant-design/icons'
import NavigationTree from './NavigationTree'
import './Sidebar.scss'

const { Sider } = Layout

interface SidebarProps {
  sidebarOpened: boolean
  onToggle: () => void
}

function Sidebar({ sidebarOpened, onToggle }: SidebarProps) {
  return (
    <Sider
      width={270}
      collapsed={!sidebarOpened}
      collapsedWidth={80}
      className="sidebar"
      theme="dark"
    >
      <div className="sidebar-header" data-collapsed={!sidebarOpened}>
        <img src="/assets/td-logo.svg" alt="TD Logo" className="td-logo-img" />
        {sidebarOpened && (
          <div className="sidebar-title-section">
            <h1 className="sidebar-title">
              LEAP <span className="version-text">1.0</span>
            </h1>
            <p className="sidebar-subtitle">Liquidity Explain & Analytics</p>
          </div>
        )}
      </div>

      <div className="navigation-tree-wrapper">
        <NavigationTree sidebarOpened={sidebarOpened} />
      </div>

      <div className="sidebar-footer">
        <button
          className="sidebar-toggle-btn"
          onClick={onToggle}
          title={sidebarOpened ? 'Collapse sidebar' : 'Expand sidebar'}
        >
          {sidebarOpened ? <MenuFoldOutlined /> : <MenuUnfoldOutlined />}
        </button>
      </div>
    </Sider>
  )
}

export default Sidebar

// leap-angular/src/app/layout/sidebar/sidebar.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.scss']
})
export class SidebarComponent {
  @Input() sidebarOpened = true;
  @Output() toggle = new EventEmitter<void>();

  toggleSidebar(): void {
    this.toggle.emit();
  }
}

<div class="sidebar">
  <!-- Sidebar Header with Logo -->
  <div class="sidebar-header" [class.sidebar-collapsed]="!sidebarOpened">
    <img src="assets/td-logo.svg" alt="TD Logo" class="td-logo-img">
    <div class="sidebar-title-section" *ngIf="sidebarOpened">
      <h1 class="sidebar-title">LEAP <span class="version-text">1.0</span></h1>
      <p class="sidebar-subtitle">Liquidity Explain & Analytics</p>
    </div>
  </div>

  <!-- Navigation Menu -->
  <app-navigation-tree [sidebarOpened]="sidebarOpened"></app-navigation-tree>

  <!-- Sidebar Toggle Button at Bottom -->
  <div class="sidebar-footer">
    <button mat-icon-button class="sidebar-toggle-btn" (click)="toggleSidebar()" matTooltip="{{ sidebarOpened ? 'Collapse sidebar' : 'Expand sidebar' }}">
      <mat-icon class="material-icons-outlined">{{ sidebarOpened ? 'keyboard_double_arrow_left' : 'keyboard_double_arrow_right' }}</mat-icon>
    </button>
  </div>
</div>
