// leap-angular/src/app/layout/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, NavigationEnd } from '@angular/router';
import { Store } from '@ngrx/store';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { selectCurrentUser } from '@core/state/auth/auth.selectors';
import { logout } from '@core/state/auth/auth.actions';
import { User } from '@core/state/auth/auth.actions';

interface Breadcrumb {
  label: string;
  url: string;
}

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {
  currentUser = {
    name: 'Yu Lin',
    role: 'Maker',
    avatar: 'YL'
  };

  user$: Observable<User | null>;
  breadcrumbs: Breadcrumb[] = [];

  constructor(
    private router: Router,
    private store: Store
  ) {
    this.user$ = this.store.select(selectCurrentUser);
    this.router.events
      .pipe(
        filter(event => event instanceof NavigationEnd),
        map(() => this.createBreadcrumbs())
      )
      .subscribe(breadcrumbs => {
        this.breadcrumbs = breadcrumbs;
      });
  }

  private createBreadcrumbs(): Breadcrumb[] {
    const url = this.router.url;
    const segments = url.split('/').filter(segment => segment);

    const breadcrumbs: Breadcrumb[] = [{ label: 'Home', url: '/dashboard' }];

    if (segments.length > 0) {
      if (segments[0] === 'dashboard') {
        breadcrumbs.push({ label: 'Dashboard', url: '/dashboard' });
      } else if (segments[0] === 'product') {
        breadcrumbs.push({ label: 'Product Analysis', url: '/product' });
        if (segments[1]) {
          breadcrumbs.push({
            label: this.formatLabel(segments[1]),
            url: `/product/${segments[1]}`
          });
        }
      } else if (segments[0] === 'regulatory') {
        breadcrumbs.push({ label: 'Regulatory Views', url: '/regulatory' });
        if (segments[1]) {
          breadcrumbs.push({
            label: segments[1].toUpperCase(),
            url: `/regulatory/${segments[1]}`
          });
        }
      } else if (segments[0] === 'maker') {
        breadcrumbs.push({ label: 'Maker Workspace', url: '/maker/review' });
      } else if (segments[0] === 'checker') {
        breadcrumbs.push({ label: 'Checker Workspace', url: '/checker/approve' });
      }
    }

    return breadcrumbs;
  }

  private formatLabel(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1).replace(/-/g, ' ');
  }

  ngOnInit(): void {
    // Subscribe to user changes
    this.user$.subscribe(user => {
      if (user) {
        this.currentUser = {
          name: user.fullName || user.username,
          role: user.role.charAt(0).toUpperCase() + user.role.slice(1),
          avatar: this.getInitials(user.fullName || user.username)
        };
      }
    });
  }

  private getInitials(name: string): string {
    return name
      .split(' ')
      .map(n => n.charAt(0))
      .join('')
      .toUpperCase()
      .substring(0, 2);
  }

  logout(): void {
    this.store.dispatch(logout());
  }

  switchToChecker(): void {
    // Switch role to Checker
    this.currentUser.role = 'Checker';
    // You can add navigation logic here if needed
    // this.router.navigate(['/checker/approve']);
  }
}

<mat-toolbar class="app-header">
  <!-- 左侧：搜索框 -->
  <div class="header-left">
    <div class="search-box">
      <mat-icon class="search-icon material-icons-outlined">search</mat-icon>
      <input type="text" class="search-input" placeholder="Search">
    </div>
  </div>

  <!-- 右侧：通知和用户信息 -->
  <div class="header-right">
    <button mat-icon-button class="notification-button" matTooltip="Notifications">
      <mat-icon [matBadge]="3" matBadgeColor="warn" matBadgeSize="small" class="material-icons-outlined">notifications</mat-icon>
    </button>

    <button mat-button [matMenuTriggerFor]="userMenu" class="user-menu-button">
      <div class="user-avatar">YL</div>
    </button>

    <mat-menu #userMenu="matMenu" xPosition="before" class="user-dropdown-menu">
      <div class="user-header">
        <div class="user-name-full">{{ currentUser.name }}</div>
        <div class="user-role">{{ currentUser.role }}</div>
      </div>
      <mat-divider></mat-divider>
      <button mat-menu-item (click)="switchToChecker()">
        <mat-icon class="material-icons-outlined">swap_horiz</mat-icon>
        <span>Switch to Checker</span>
      </button>
      <button mat-menu-item>
        <mat-icon class="material-icons-outlined">person</mat-icon>
        <span>Profile</span>
      </button>
      <button mat-menu-item>
        <mat-icon class="material-icons-outlined">settings</mat-icon>
        <span>Settings</span>
      </button>
      <mat-divider></mat-divider>
      <button mat-menu-item (click)="logout()">
        <mat-icon class="material-icons-outlined">logout</mat-icon>
        <span>Logout</span>
      </button>
    </mat-menu>
  </div>
</mat-toolbar>

// leap-angular/src/components/layout/Header.tsx
import { useEffect, useState } from 'react'
import { useNavigate, useLocation } from 'react-router-dom'
import { Layout, Badge, Dropdown, MenuProps, Avatar } from 'antd'
import { SearchOutlined, BellOutlined, SwapOutlined, UserOutlined, SettingOutlined, LogoutOutlined } from '@ant-design/icons'
import { useAppDispatch, useAppSelector } from '@store/hooks'
import { logoutAsync } from '@store/slices/authSlice'
import { TDInput } from '@components/shared'
import './Header.scss'

const { Header: AntHeader } = Layout

type ViewMode = 'maker' | 'checker'

function Header() {
  const navigate = useNavigate()
  const location = useLocation()
  const dispatch = useAppDispatch()
  const user = useAppSelector((state) => state.auth.user)
  const [searchValue, setSearchValue] = useState('')

  // Determine current view mode from route
  const getCurrentViewMode = (): ViewMode => {
    if (location.pathname.includes('/checker')) {
      return 'checker'
    }
    return 'maker'
  }

  const [currentViewMode, setCurrentViewMode] = useState<ViewMode>(getCurrentViewMode())
  const [currentUser, setCurrentUser] = useState({
    name: 'Yu Lin',
    role: 'Maker',
    avatar: 'YL',
  })

  useEffect(() => {
    setCurrentViewMode(getCurrentViewMode())
  }, [location.pathname])

  useEffect(() => {
    if (user) {
      setCurrentUser({
        name: user.fullName || user.username,
        role: user.role.charAt(0).toUpperCase() + user.role.slice(1),
        avatar: getInitials(user.fullName || user.username),
      })
    }
  }, [user])

  const getInitials = (name: string): string => {
    return name
      .split(' ')
      .map((n) => n.charAt(0))
      .join('')
      .toUpperCase()
      .substring(0, 2)
  }

  const handleLogout = () => {
    dispatch(logoutAsync())
    navigate('/login')
  }

  const switchToMaker = () => {
    setCurrentViewMode('maker')
    navigate('/maker/review')
  }

  const switchToChecker = () => {
    setCurrentViewMode('checker')
    navigate('/checker/approve')
  }

  const menuItems: MenuProps['items'] = [
    ...(currentViewMode === 'maker' ? [
      {
        key: 'switch-to-checker',
        icon: <SwapOutlined />,
        label: 'Switch to Checker View',
        onClick: switchToChecker,
      },
    ] : [
      {
        key: 'switch-to-maker',
        icon: <SwapOutlined />,
        label: 'Switch to Maker View',
        onClick: switchToMaker,
      },
    ]),
    {
      key: 'profile',
      icon: <UserOutlined />,
      label: 'Profile',
    },
    {
      key: 'settings',
      icon: <SettingOutlined />,
      label: 'Settings',
    },
    {
      type: 'divider',
    },
    {
      key: 'logout',
      icon: <LogoutOutlined />,
      label: 'Logout',
      onClick: handleLogout,
    },
  ]

  return (
    <AntHeader className="app-header">
      <div className="header-left">
        <div className="search-box">
          <TDInput
            className="search-input"
            placeholder="Search"
            label=" " // Space to disable floating label, will be hidden
            value={searchValue}
            onChange={(e) => setSearchValue(e.currentTarget.value)}
            leading={{
              content: <SearchOutlined className="search-icon" />,
              type: 'icon'
            }}
            clearBtn={{
              a11yDesc: 'Clear search',
              onClick: () => setSearchValue('')
            }}
          />
        </div>
      </div>

      <div className="header-right">
        <Badge count={3} size="small">
          <button className="notification-button">
            <BellOutlined />
          </button>
        </Badge>

        <Dropdown
          menu={{ items: menuItems }}
          placement="bottomRight"
          overlayClassName="user-dropdown-menu"
        >
          <button className="user-menu-button">
            <Avatar className="user-avatar">{currentUser.avatar}</Avatar>
          </button>
        </Dropdown>
      </div>
    </AntHeader>
  )
}

export default Header
