// leap-angular/src/app/layout/main-layout/main-layout.component.ts
import { BreakpointObserver } from '@angular/cdk/layout';
import { Component, OnDestroy } from '@angular/core';
import { Subject, takeUntil } from 'rxjs';

@Component({
  selector: 'app-main-layout',
  templateUrl: './main-layout.component.html',
  styleUrls: ['./main-layout.component.scss']
})
export class MainLayoutComponent implements OnDestroy {
  sidebarOpened = true;
  private destroy$ = new Subject<void>();

  constructor(private breakpointObserver: BreakpointObserver) {
    // Sidebar always visible, no toggle needed
  }

  onSidebarToggle(): void {
    this.sidebarOpened = !this.sidebarOpened;
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }
}

<div class="main-layout">
  <div class="sidebar-wrapper" [class.sidebar-collapsed]="!sidebarOpened">
    <app-sidebar [sidebarOpened]="sidebarOpened" (toggle)="onSidebarToggle()"></app-sidebar>
  </div>

  <div class="content-area">
    <app-header></app-header>
    <div class="main-content-wrapper">
      <router-outlet></router-outlet>
    </div>
  </div>
</div>

// leap-angular/src/components/layout/MainLayout.tsx
import { useState } from 'react'
import { Outlet } from 'react-router-dom'
import { Layout } from 'antd'
import Sidebar from './Sidebar'
import Header from './Header'
import './MainLayout.scss'

const { Content } = Layout

function MainLayout() {
  const [sidebarOpened, setSidebarOpened] = useState(true)

  const handleSidebarToggle = () => {
    setSidebarOpened(!sidebarOpened)
  }

  return (
    <Layout className="main-layout">
      <Sidebar sidebarOpened={sidebarOpened} onToggle={handleSidebarToggle} />
      <Layout className="content-area">
        <Header />
        <Content className="main-content-wrapper">
          <Outlet />
        </Content>
      </Layout>
    </Layout>
  )
}

export default MainLayout
